/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ACER
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form PegawaiView
     */
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        footerPanel = new javax.swing.JPanel();
        anggotaLabel = new javax.swing.JLabel();
        anggotaLabel2 = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        ReservasiPanel = new javax.swing.JPanel();
        customerIcon = new javax.swing.JLabel();
        customerlabel1 = new javax.swing.JLabel();
        PegawaiPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        customerlabel = new javax.swing.JLabel();
        welcomeIcon = new javax.swing.JLabel();
        hotelIcon = new javax.swing.JLabel();
        headerPanel = new javax.swing.JPanel();
        tugasBesar = new javax.swing.JLabel();
        kelasD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        footerPanel.setBackground(new java.awt.Color(102, 153, 0));
        footerPanel.setForeground(new java.awt.Color(102, 153, 0));
        footerPanel.setPreferredSize(new java.awt.Dimension(100, 338));

        anggotaLabel.setBackground(new java.awt.Color(255, 255, 255));
        anggotaLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        anggotaLabel.setForeground(new java.awt.Color(255, 255, 255));
        anggotaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anggotaLabel.setText("200710781 Henri || 200710789  Jessica Amadea Rahma ||  200710792  Yosef Lintang Dananjaya ");
        anggotaLabel.setToolTipText("");
        anggotaLabel.setPreferredSize(new java.awt.Dimension(100, 338));

        anggotaLabel2.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        anggotaLabel2.setForeground(new java.awt.Color(255, 255, 255));
        anggotaLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anggotaLabel2.setText("200710803 Richard Bryan Raffaello || 200710820 Willy Christian Chia  ");

        javax.swing.GroupLayout footerPanelLayout = new javax.swing.GroupLayout(footerPanel);
        footerPanel.setLayout(footerPanelLayout);
        footerPanelLayout.setHorizontalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addGroup(footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anggotaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(anggotaLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        footerPanelLayout.setVerticalGroup(
            footerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anggotaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anggotaLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        centerPanel.setBackground(new java.awt.Color(234, 239, 234));

        ReservasiPanel.setBackground(new java.awt.Color(102, 153, 0));
        ReservasiPanel.setPreferredSize(new java.awt.Dimension(127, 163));
        ReservasiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReservasiPanelMouseClicked(evt);
            }
        });

        customerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/book.png"))); // NOI18N

        customerlabel1.setBackground(new java.awt.Color(255, 255, 255));
        customerlabel1.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        customerlabel1.setForeground(new java.awt.Color(255, 255, 255));
        customerlabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerlabel1.setText("Reservasi");

        javax.swing.GroupLayout ReservasiPanelLayout = new javax.swing.GroupLayout(ReservasiPanel);
        ReservasiPanel.setLayout(ReservasiPanelLayout);
        ReservasiPanelLayout.setHorizontalGroup(
            ReservasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(customerlabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
            .addComponent(customerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ReservasiPanelLayout.setVerticalGroup(
            ReservasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservasiPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(customerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerlabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        PegawaiPanel.setBackground(new java.awt.Color(102, 153, 0));
        PegawaiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PegawaiPanelMouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lecturer.png"))); // NOI18N

        customerlabel.setBackground(new java.awt.Color(255, 255, 255));
        customerlabel.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        customerlabel.setForeground(new java.awt.Color(255, 255, 255));
        customerlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        customerlabel.setText("Pegawai");

        javax.swing.GroupLayout PegawaiPanelLayout = new javax.swing.GroupLayout(PegawaiPanel);
        PegawaiPanel.setLayout(PegawaiPanelLayout);
        PegawaiPanelLayout.setHorizontalGroup(
            PegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(customerlabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );
        PegawaiPanelLayout.setVerticalGroup(
            PegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PegawaiPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        welcomeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hotel.png"))); // NOI18N
        welcomeIcon.setText("jLabel4");

        hotelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/welcome.png"))); // NOI18N
        hotelIcon.setText(".");

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerPanelLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(hotelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(PegawaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ReservasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(welcomeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ReservasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PegawaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, centerPanelLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(hotelIcon)
                .addGap(31, 31, 31))
        );

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        tugasBesar.setFont(new java.awt.Font("Futura Md BT", 1, 30)); // NOI18N
        tugasBesar.setForeground(new java.awt.Color(0, 0, 0));
        tugasBesar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tugasBesar.setText("Tugas Besar Pemograman Berbasis Objek");

        kelasD.setFont(new java.awt.Font("Futura Md BT", 1, 36)); // NOI18N
        kelasD.setForeground(new java.awt.Color(0, 0, 0));
        kelasD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kelasD.setText("Kelas D");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tugasBesar, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kelasD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(tugasBesar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kelasD)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(footerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(footerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PegawaiPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PegawaiPanelMouseClicked
        LoginView lv = new LoginView();
        this.dispose();
        lv.setVisible(true);
    }//GEN-LAST:event_PegawaiPanelMouseClicked

    private void ReservasiPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReservasiPanelMouseClicked
        ReservasiView rv = new ReservasiView();
        this.dispose();
        rv.setVisible(true);
    }//GEN-LAST:event_ReservasiPanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PegawaiPanel;
    private javax.swing.JPanel ReservasiPanel;
    private javax.swing.JLabel anggotaLabel;
    private javax.swing.JLabel anggotaLabel2;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel customerIcon;
    private javax.swing.JLabel customerlabel;
    private javax.swing.JLabel customerlabel1;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel hotelIcon;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel kelasD;
    private javax.swing.JLabel tugasBesar;
    private javax.swing.JLabel welcomeIcon;
    // End of variables declaration//GEN-END:variables
}
