package view;

import control.PegawaiControl;
import exception.IDInvalidException;
import exception.InputKosongException;
import exception.PilihanKosongException;
import javax.swing.JOptionPane; 
import model.Pegawai;

public class PegawaiView extends javax.swing.JFrame {
    private PegawaiControl pegawaiControl;
    String action = null;
    
    public PegawaiView() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        pegawaiControl = new PegawaiControl();
        showPegawai();
    }
    
    public void setComponent(boolean value){

        idInput.setEnabled(value);
        namaInput.setEnabled(value);
        roleInput.setEnabled(value);
        noTelpInput.setEnabled(value);
        
        jRadioPria.setEnabled(value);
        jRadioWanita.setEnabled(value);

        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
    }
    
    public void setEditDeleteBtn(boolean value){
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void clearText(){
        idInput.setText("");
        namaInput.setText("");
        roleInput.setText("");
        noTelpInput.setText("");
        searchInput.setText("");
    }
    
    public void showPegawai(){
        showDataTextAreaPegawai.setText(pegawaiControl.showDataPegawai());
    }
    
    public void idInvalidException() throws IDInvalidException{
        if(idInput.getText().length()<5 || idInput.getText().length()>7){
            throw new IDInvalidException();
        }
    }
    
    public void pilihanKosongException() throws PilihanKosongException{
        if(!jRadioPria.isSelected() || !jRadioWanita.isSelected()){
            throw new PilihanKosongException();
        }
    }
    
    public void inputKosongException() throws InputKosongException{
        if(idInput.getText().isEmpty() || namaInput.getText().isEmpty()
                    || roleInput.getText().isEmpty()
                    || noTelpInput.getText().isEmpty()) {
            throw new InputKosongException();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexBtnGroup = new javax.swing.ButtonGroup();
        headerPegawaiPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        homeicon = new javax.swing.JLabel();
        homelabel = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        headerPegawai1 = new javax.swing.JPanel();
        pegawaiLabel = new javax.swing.JLabel();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        headerPegawai2 = new javax.swing.JPanel();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        header2Panel = new javax.swing.JPanel();
        idPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        namaPanel = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        namaInput = new javax.swing.JTextField();
        jabatanPanel = new javax.swing.JPanel();
        roleLabel = new javax.swing.JLabel();
        roleInput = new javax.swing.JTextField();
        sexPanel = new javax.swing.JPanel();
        sexLabel = new javax.swing.JLabel();
        jRadioPria = new javax.swing.JRadioButton();
        jRadioWanita = new javax.swing.JRadioButton();
        noTelpPanel = new javax.swing.JPanel();
        noTelprLabel = new javax.swing.JLabel();
        noTelpInput = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showDataTextAreaPegawai = new javax.swing.JTextArea();
        tampilanLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPegawaiPanel.setBackground(new java.awt.Color(255, 255, 255));

        homePanel.setBackground(new java.awt.Color(102, 153, 0));
        homePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePanelMouseClicked(evt);
            }
        });

        homeicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N

        homelabel.setBackground(new java.awt.Color(255, 255, 255));
        homelabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        homelabel.setForeground(new java.awt.Color(255, 255, 255));
        homelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homelabel.setText("Home");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeicon, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
            .addComponent(homelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(homeicon, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homelabel)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        TitleLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hotel.png"))); // NOI18N
        TitleLabel.setText(".");

        javax.swing.GroupLayout headerPegawaiPanelLayout = new javax.swing.GroupLayout(headerPegawaiPanel);
        headerPegawaiPanel.setLayout(headerPegawaiPanelLayout);
        headerPegawaiPanelLayout.setHorizontalGroup(
            headerPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPegawaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        headerPegawaiPanelLayout.setVerticalGroup(
            headerPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPegawaiPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TitleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        headerPegawai1.setBackground(new java.awt.Color(234, 239, 234));
        headerPegawai1.setForeground(new java.awt.Color(255, 255, 255));
        headerPegawai1.setPreferredSize(new java.awt.Dimension(801, 103));

        pegawaiLabel.setFont(new java.awt.Font("Futura Md BT", 1, 36)); // NOI18N
        pegawaiLabel.setForeground(new java.awt.Color(0, 0, 0));
        pegawaiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pegawaiLabel.setText(" Pegawai");

        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(22, 52, 122));
        searchBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Cari");
        searchBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        searchBtn.setBorderPainted(false);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPegawai1Layout = new javax.swing.GroupLayout(headerPegawai1);
        headerPegawai1.setLayout(headerPegawai1Layout);
        headerPegawai1Layout.setHorizontalGroup(
            headerPegawai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPegawai1Layout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addComponent(pegawaiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerPegawai1Layout.setVerticalGroup(
            headerPegawai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPegawai1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(pegawaiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headerPegawai1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        headerPegawai2.setBackground(new java.awt.Color(234, 239, 234));
        headerPegawai2.setForeground(new java.awt.Color(255, 255, 255));
        headerPegawai2.setPreferredSize(new java.awt.Dimension(801, 103));

        editBtn.setBackground(new java.awt.Color(236, 168, 30));
        editBtn.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Ubah");
        editBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        editBtn.setBorderPainted(false);
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(153, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Hapus");
        deleteBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        deleteBtn.setBorderPainted(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(0, 153, 0));
        addBtn.setFont(new java.awt.Font("Berlin Sans FB", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Tambah");
        addBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        addBtn.setBorderPainted(false);
        addBtn.setDefaultCapable(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerPegawai2Layout = new javax.swing.GroupLayout(headerPegawai2);
        headerPegawai2.setLayout(headerPegawai2Layout);
        headerPegawai2Layout.setHorizontalGroup(
            headerPegawai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPegawai2Layout.createSequentialGroup()
                .addGroup(headerPegawai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerPegawai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(headerPegawai2Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPegawai2Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        headerPegawai2Layout.setVerticalGroup(
            headerPegawai2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPegawai2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        header2Panel.setBackground(new java.awt.Color(234, 239, 234));

        idPanel.setBackground(new java.awt.Color(234, 239, 234));

        idLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(0, 0, 0));
        idLabel.setText("Id Pegawai");

        idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idPanelLayout = new javax.swing.GroupLayout(idPanel);
        idPanel.setLayout(idPanelLayout);
        idPanelLayout.setHorizontalGroup(
            idPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        idPanelLayout.setVerticalGroup(
            idPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        namaPanel.setBackground(new java.awt.Color(234, 239, 234));
        namaPanel.setPreferredSize(new java.awt.Dimension(289, 58));

        namaLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaLabel.setText("Nama Pegawai");

        namaInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaPanelLayout = new javax.swing.GroupLayout(namaPanel);
        namaPanel.setLayout(namaPanelLayout);
        namaPanelLayout.setHorizontalGroup(
            namaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(namaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namaPanelLayout.setVerticalGroup(
            namaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namaInput)
                .addContainerGap())
        );

        jabatanPanel.setBackground(new java.awt.Color(234, 239, 234));
        jabatanPanel.setPreferredSize(new java.awt.Dimension(282, 58));

        roleLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(0, 0, 0));
        roleLabel.setText("Jabatan Pegawai");

        javax.swing.GroupLayout jabatanPanelLayout = new javax.swing.GroupLayout(jabatanPanel);
        jabatanPanel.setLayout(jabatanPanelLayout);
        jabatanPanelLayout.setHorizontalGroup(
            jabatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jabatanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jabatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jabatanPanelLayout.setVerticalGroup(
            jabatanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jabatanPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(roleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roleInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        sexPanel.setBackground(new java.awt.Color(234, 239, 234));

        sexLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        sexLabel.setForeground(new java.awt.Color(0, 0, 0));
        sexLabel.setText("Jenis Kelamin");

        jRadioPria.setBackground(new java.awt.Color(234, 239, 234));
        sexBtnGroup.add(jRadioPria);
        jRadioPria.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        jRadioPria.setForeground(new java.awt.Color(0, 0, 0));
        jRadioPria.setText("Pria");
        jRadioPria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioPriaActionPerformed(evt);
            }
        });

        jRadioWanita.setBackground(new java.awt.Color(234, 239, 234));
        sexBtnGroup.add(jRadioWanita);
        jRadioWanita.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        jRadioWanita.setForeground(new java.awt.Color(0, 0, 0));
        jRadioWanita.setText("Wanita");
        jRadioWanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioWanitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sexPanelLayout = new javax.swing.GroupLayout(sexPanel);
        sexPanel.setLayout(sexPanelLayout);
        sexPanelLayout.setHorizontalGroup(
            sexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sexPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sexPanelLayout.createSequentialGroup()
                        .addComponent(jRadioPria, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioWanita))
                    .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sexPanelLayout.setVerticalGroup(
            sexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sexPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(sexPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioPria)
                    .addComponent(jRadioWanita))
                .addContainerGap())
        );

        noTelpPanel.setBackground(new java.awt.Color(234, 239, 234));

        noTelprLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        noTelprLabel.setForeground(new java.awt.Color(0, 0, 0));
        noTelprLabel.setText("Nomor Telepon ");

        javax.swing.GroupLayout noTelpPanelLayout = new javax.swing.GroupLayout(noTelpPanel);
        noTelpPanel.setLayout(noTelpPanelLayout);
        noTelpPanelLayout.setHorizontalGroup(
            noTelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noTelpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noTelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noTelprLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noTelpInput, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        noTelpPanelLayout.setVerticalGroup(
            noTelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noTelpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noTelprLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(noTelpInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        cancelBtn.setBackground(new java.awt.Color(153, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Batal");
        cancelBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        cancelBtn.setBorderPainted(false);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(22, 52, 122));
        saveBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Simpan");
        saveBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        saveBtn.setBorderPainted(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        showDataTextAreaPegawai.setColumns(20);
        showDataTextAreaPegawai.setRows(5);
        showDataTextAreaPegawai.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        showDataTextAreaPegawai.setCaretColor(new java.awt.Color(102, 153, 0));
        jScrollPane1.setViewportView(showDataTextAreaPegawai);

        tampilanLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        tampilanLabel.setForeground(new java.awt.Color(0, 0, 0));
        tampilanLabel.setText("Daftar Pegawai Hotel");

        javax.swing.GroupLayout header2PanelLayout = new javax.swing.GroupLayout(header2Panel);
        header2Panel.setLayout(header2PanelLayout);
        header2PanelLayout.setHorizontalGroup(
            header2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header2PanelLayout.createSequentialGroup()
                .addGroup(header2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(header2PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(idPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header2PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(header2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tampilanLabel)
                            .addGroup(header2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(namaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jabatanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)))))
                .addGap(109, 109, 109)
                .addGroup(header2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sexPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noTelpPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header2PanelLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(header2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(header2PanelLayout.createSequentialGroup()
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        header2PanelLayout.setVerticalGroup(
            header2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(header2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sexPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(header2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(header2PanelLayout.createSequentialGroup()
                        .addComponent(noTelpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(header2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(header2PanelLayout.createSequentialGroup()
                        .addComponent(namaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jabatanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(tampilanLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPegawaiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headerPegawai2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(headerPegawai1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(header2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPegawaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(headerPegawai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerPegawai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(header2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void jRadioWanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioWanitaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioWanitaActionPerformed

    private void namaInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaInputActionPerformed

    private void idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInputActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try{
            inputKosongException();
            idInvalidException();
            
            String jenisKelamin = "";
            
            if(jRadioPria.isSelected()==true){
                jenisKelamin = "Pria";
            }else if(jRadioWanita.isSelected()==true){
                jenisKelamin = "Wanita";
            }else{
                pilihanKosongException();
            }
            
            
            Pegawai p = new Pegawai(idInput.getText(), 
                                    namaInput.getText(), 
                                    roleInput.getText(), 
                                    jenisKelamin,
                                    noTelpInput.getText());

            if(action.equals("Tambah")){
                pegawaiControl.insertDataPegawai(p);
                JOptionPane.showMessageDialog(this, "Data Pegawai berhasil ditambah!");
            }else if(action.equals("Ubah")){
                pegawaiControl.updateDataPegawai(p, idInput.getText());
                JOptionPane.showMessageDialog(this, "Data Pegawai berhasil diupdate!");
            }
            jRadioPria.setEnabled(false);
            jRadioWanita.setEnabled(false);
            clearText();
            showPegawai();
            setComponent(false);
            setEditDeleteBtn(false);
        }catch (InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch (IDInvalidException e2){
            JOptionPane.showMessageDialog(this, e2.message());
        }catch (PilihanKosongException e3){
            JOptionPane.showMessageDialog(this, e3.message());
        }catch (Exception e){}
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        sexBtnGroup.clearSelection();
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void jRadioPriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioPriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioPriaActionPerformed

    private void homePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMouseClicked
        HomeView hv = new HomeView();
        this.dispose();
        hv.setVisible(true);
    }//GEN-LAST:event_homePanelMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,
            "Apakah yakin ingin menambah data Pegawai? ", "Konfirmasi",
            JOptionPane.YES_NO_OPTION);
        
        if(getAnswer == JOptionPane.YES_OPTION){
            try{
                setComponent(true);
                clearText();
                searchInput.setText("");
                action = "Tambah";
            }catch(Exception  e){
                System.out.println("Error : " + e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Data tidak jadi ditambah!");
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,
            "Apakah yakin ingin mengubah data Pegawai? ", "Konfirmasi",
            JOptionPane.YES_NO_OPTION);
        
        if(getAnswer == JOptionPane.YES_OPTION){
            setComponent(true);
            action = "Ubah";
        }else{
            JOptionPane.showMessageDialog(null, "Data Pegawai tidak jadi diubah!");
        }
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,
            "Apakah yakin ingin menghapus data Pegawai? ", "Konfirmasi",
            JOptionPane.YES_NO_OPTION);
        
        if(getAnswer == JOptionPane.YES_OPTION){
            try{
                pegawaiControl.deleteDataPegawai(idInput.getText());
                clearText();
                sexBtnGroup.clearSelection();
                showPegawai();
                JOptionPane.showMessageDialog(null, "Data Pegawai berhasil dihapus!");
            }catch(Exception  e){
                System.out.println("Error : " + e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Data Pegawai tidak jadi dihapus!");
        }
        setComponent(true);
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        setEditDeleteBtn(true);
        setComponent(false);
        
        try{
            Pegawai pegawai = pegawaiControl.searchPegawai(searchInput.getText());
            if(pegawai == null){
                clearText();
                sexBtnGroup.clearSelection();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan!",
                     "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
                idInput.setText(pegawai.getId());
                namaInput.setText(pegawai.getNama());
                roleInput.setText(pegawai.getRole());
                noTelpInput.setText(pegawai.getNo_telp());
                
                if(pegawai.getJenis_kelamin().equalsIgnoreCase("Pria")){
                    jRadioPria.setSelected(true);
                }else{
                    jRadioWanita.setSelected(true);
                }
            }
        }catch(Exception e){
            System.out.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PegawaiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PegawaiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PegawaiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PegawaiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PegawaiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel header2Panel;
    private javax.swing.JPanel headerPegawai1;
    private javax.swing.JPanel headerPegawai2;
    private javax.swing.JPanel headerPegawaiPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel homeicon;
    private javax.swing.JLabel homelabel;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel idPanel;
    private javax.swing.JRadioButton jRadioPria;
    private javax.swing.JRadioButton jRadioWanita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jabatanPanel;
    private javax.swing.JTextField namaInput;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JPanel namaPanel;
    private javax.swing.JTextField noTelpInput;
    private javax.swing.JPanel noTelpPanel;
    private javax.swing.JLabel noTelprLabel;
    private javax.swing.JLabel pegawaiLabel;
    private javax.swing.JTextField roleInput;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.ButtonGroup sexBtnGroup;
    private javax.swing.JLabel sexLabel;
    private javax.swing.JPanel sexPanel;
    private javax.swing.JTextArea showDataTextAreaPegawai;
    private javax.swing.JLabel tampilanLabel;
    // End of variables declaration//GEN-END:variables
}
