package view;

import control.ReservasiControl;
import control.PegawaiControl;
import control.TamuControl;
import exception.InputKosongException;
import exception.NumberFormatException;
import java.util.List;
import javax.swing.JOptionPane; 
import javax.swing.table.TableModel;
import model.Reservasi;
import model.Pegawai;
import model.Tamu;
import table.TableReservasi;

public class ReservasiView extends javax.swing.JFrame {
    private ReservasiControl reservasiControl;
    private PegawaiControl pegawaiControl;
    private TamuControl tamuControl;
    List<Pegawai> listPegawai;
    List<Tamu> listTamu;
    String action = null;
    int selectedId = 0;
    
    public ReservasiView() {
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        reservasiControl = new ReservasiControl();
        pegawaiControl = new PegawaiControl();
        tamuControl = new TamuControl();
        showReservasi();
        setPegawaiToDropDown();
        setTamuToDropDown();
    }
    
    public void setPegawaiToDropDown(){
        listPegawai = pegawaiControl.showListPegawai();
        for(int i=0; i<listPegawai.size(); i++){
            pegawaiDropDown.addItem(listPegawai.get(i));
        }
    }
    
    public void setTamuToDropDown(){
        listTamu = tamuControl.showListTamu();
        for(int i=0; i<listTamu.size(); i++){
            tamuDropDown.addItem(listTamu.get(i));
        }
    }
     
    public void setComponent(boolean value){
        tglCheckInput.setEnabled(value);
        jmlTamuInput.setEnabled(value);
        durasiInput.setEnabled(value);
        tglResInput.setEnabled(value);
        
        pegawaiDropDown.setEnabled(value);
        tamuDropDown.setEnabled(value);
        
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
    }
     
    public void setEditDeleteBtn(boolean value){
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
     
    public void clearText(){
        tglCheckInput.setText("");
        jmlTamuInput.setText("");
        durasiInput.setText("");
        tglResInput.setText("");
        
        pegawaiDropDown.setSelectedItem(ABORT);
        tamuDropDown.setSelectedItem(ABORT);
        
        searchInput.setText("");
    }
    
    public void showReservasi(){
        tableReservasi.setModel(reservasiControl.showReservasi(""));
    }
    
    public void numberFormatException() throws NumberFormatException{
        if(durasiInput.getText().contains("[a-zA-Z]+") || jmlTamuInput.getText().contains("[a-zA-Z]+")){
            throw new NumberFormatException();
        }
    } 
    
    public void inputKosongException() throws InputKosongException{
        if(tglCheckInput.getText().isEmpty() || 
                jmlTamuInput.getText().isEmpty() ||
                durasiInput.getText().isEmpty() ||
                pegawaiDropDown.getSelectedIndex()==-1 || 
                tamuDropDown.getSelectedIndex()==-1){
            throw new InputKosongException();
        }
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPegawaiPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        homeIcon = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        transaksiPanel = new javax.swing.JPanel();
        transaksiIcon = new javax.swing.JLabel();
        transaksiLabel = new javax.swing.JLabel();
        hotelIcon = new javax.swing.JLabel();
        headerReservasi = new javax.swing.JPanel();
        reservasiLabel = new javax.swing.JLabel();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        headerReservasi1 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        pegawaiPanel = new javax.swing.JPanel();
        pegawaiLabel = new javax.swing.JLabel();
        pegawaiDropDown = new javax.swing.JComboBox<>();
        tamuPanel = new javax.swing.JPanel();
        tamuLabel = new javax.swing.JLabel();
        tamuDropDown = new javax.swing.JComboBox<>();
        tanggalPanel = new javax.swing.JPanel();
        tglCheckLabel = new javax.swing.JLabel();
        tglCheckInput = new javax.swing.JTextField();
        durasiPanel = new javax.swing.JPanel();
        durasiLabel = new javax.swing.JLabel();
        durasiInput = new javax.swing.JTextField();
        reservasiPanel = new javax.swing.JPanel();
        tglResLabel = new javax.swing.JLabel();
        tglResInput = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReservasi = new javax.swing.JTable();
        jmlTamuPanel = new javax.swing.JPanel();
        jmlTamuLabel = new javax.swing.JLabel();
        jmlTamuInput = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPegawaiPanel.setBackground(new java.awt.Color(255, 255, 255));

        homePanel.setBackground(new java.awt.Color(102, 153, 0));
        homePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePanelMouseClicked(evt);
            }
        });

        homeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N

        homeLabel.setBackground(new java.awt.Color(255, 255, 255));
        homeLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLabel.setText("Home");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(homeIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homeLabel)
                .addGap(12, 12, 12))
        );

        transaksiPanel.setBackground(new java.awt.Color(102, 153, 0));
        transaksiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transaksiPanelMouseClicked(evt);
            }
        });

        transaksiIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transaksiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/lecturer.png"))); // NOI18N

        transaksiLabel.setBackground(new java.awt.Color(255, 255, 255));
        transaksiLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        transaksiLabel.setForeground(new java.awt.Color(255, 255, 255));
        transaksiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transaksiLabel.setText("Transaksi ");

        javax.swing.GroupLayout transaksiPanelLayout = new javax.swing.GroupLayout(transaksiPanel);
        transaksiPanel.setLayout(transaksiPanelLayout);
        transaksiPanelLayout.setHorizontalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transaksiIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(transaksiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );
        transaksiPanelLayout.setVerticalGroup(
            transaksiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(transaksiIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transaksiLabel)
                .addGap(12, 12, 12))
        );

        hotelIcon.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        hotelIcon.setForeground(new java.awt.Color(255, 255, 255));
        hotelIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hotel.png"))); // NOI18N
        hotelIcon.setText(".");

        javax.swing.GroupLayout headerPegawaiPanelLayout = new javax.swing.GroupLayout(headerPegawaiPanel);
        headerPegawaiPanel.setLayout(headerPegawaiPanelLayout);
        headerPegawaiPanelLayout.setHorizontalGroup(
            headerPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPegawaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hotelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transaksiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        headerPegawaiPanelLayout.setVerticalGroup(
            headerPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPegawaiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hotelIcon)
                .addGap(20, 20, 20))
            .addComponent(transaksiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        headerReservasi.setBackground(new java.awt.Color(234, 239, 234));
        headerReservasi.setForeground(new java.awt.Color(255, 255, 255));
        headerReservasi.setPreferredSize(new java.awt.Dimension(801, 103));

        reservasiLabel.setFont(new java.awt.Font("Futura Md BT", 1, 36)); // NOI18N
        reservasiLabel.setForeground(new java.awt.Color(0, 0, 0));
        reservasiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reservasiLabel.setText(" Reservasi");

        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(22, 52, 122));
        searchBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Cari");
        searchBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        searchBtn.setBorderPainted(false);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerReservasiLayout = new javax.swing.GroupLayout(headerReservasi);
        headerReservasi.setLayout(headerReservasiLayout);
        headerReservasiLayout.setHorizontalGroup(
            headerReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerReservasiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addComponent(reservasiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
        );
        headerReservasiLayout.setVerticalGroup(
            headerReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerReservasiLayout.createSequentialGroup()
                .addComponent(reservasiLabel)
                .addGap(10, 10, 10)
                .addGroup(headerReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        headerReservasi1.setBackground(new java.awt.Color(234, 239, 234));
        headerReservasi1.setForeground(new java.awt.Color(255, 255, 255));
        headerReservasi1.setPreferredSize(new java.awt.Dimension(801, 103));

        addBtn.setBackground(new java.awt.Color(0, 153, 0));
        addBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Tambah");
        addBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        addBtn.setBorderPainted(false);
        addBtn.setDefaultCapable(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(236, 168, 30));
        editBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Ubah");
        editBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        editBtn.setBorderPainted(false);
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(153, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Hapus");
        deleteBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        deleteBtn.setBorderPainted(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerReservasi1Layout = new javax.swing.GroupLayout(headerReservasi1);
        headerReservasi1.setLayout(headerReservasi1Layout);
        headerReservasi1Layout.setHorizontalGroup(
            headerReservasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerReservasi1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(headerReservasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerReservasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        headerReservasi1Layout.setVerticalGroup(
            headerReservasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerReservasi1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        contentPanel.setBackground(new java.awt.Color(234, 239, 234));

        pegawaiPanel.setBackground(new java.awt.Color(234, 239, 234));

        pegawaiLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        pegawaiLabel.setForeground(new java.awt.Color(0, 0, 0));
        pegawaiLabel.setText("Id Pegawai");

        pegawaiDropDown.setEditable(true);
        pegawaiDropDown.setForeground(new java.awt.Color(255, 255, 255));
        pegawaiDropDown.setBorder(null);
        pegawaiDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegawaiDropDownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pegawaiPanelLayout = new javax.swing.GroupLayout(pegawaiPanel);
        pegawaiPanel.setLayout(pegawaiPanelLayout);
        pegawaiPanelLayout.setHorizontalGroup(
            pegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pegawaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pegawaiDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pegawaiPanelLayout.createSequentialGroup()
                        .addComponent(pegawaiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 162, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pegawaiPanelLayout.setVerticalGroup(
            pegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pegawaiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pegawaiLabel)
                .addGap(4, 4, 4)
                .addComponent(pegawaiDropDown, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        tamuPanel.setBackground(new java.awt.Color(234, 239, 234));

        tamuLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        tamuLabel.setForeground(new java.awt.Color(0, 0, 0));
        tamuLabel.setText("Id Tamu ");

        tamuDropDown.setEditable(true);
        tamuDropDown.setBorder(null);

        javax.swing.GroupLayout tamuPanelLayout = new javax.swing.GroupLayout(tamuPanel);
        tamuPanel.setLayout(tamuPanelLayout);
        tamuPanelLayout.setHorizontalGroup(
            tamuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tamuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tamuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tamuPanelLayout.createSequentialGroup()
                        .addComponent(tamuDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(tamuPanelLayout.createSequentialGroup()
                        .addComponent(tamuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 168, Short.MAX_VALUE))))
        );
        tamuPanelLayout.setVerticalGroup(
            tamuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tamuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tamuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tamuDropDown)
                .addContainerGap())
        );

        tanggalPanel.setBackground(new java.awt.Color(234, 239, 234));

        tglCheckLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        tglCheckLabel.setForeground(new java.awt.Color(0, 0, 0));
        tglCheckLabel.setText("Tanggal Checkin");

        tglCheckInput.setText("dd/mm/yyyy");

        javax.swing.GroupLayout tanggalPanelLayout = new javax.swing.GroupLayout(tanggalPanel);
        tanggalPanel.setLayout(tanggalPanelLayout);
        tanggalPanelLayout.setHorizontalGroup(
            tanggalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tanggalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tglCheckInput, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tanggalPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tglCheckLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tanggalPanelLayout.setVerticalGroup(
            tanggalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tanggalPanelLayout.createSequentialGroup()
                .addComponent(tglCheckLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglCheckInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        durasiPanel.setBackground(new java.awt.Color(234, 239, 234));

        durasiLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        durasiLabel.setForeground(new java.awt.Color(0, 0, 0));
        durasiLabel.setText("Durasi Menginap");

        javax.swing.GroupLayout durasiPanelLayout = new javax.swing.GroupLayout(durasiPanel);
        durasiPanel.setLayout(durasiPanelLayout);
        durasiPanelLayout.setHorizontalGroup(
            durasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(durasiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(durasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(durasiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durasiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        durasiPanelLayout.setVerticalGroup(
            durasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(durasiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(durasiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(durasiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        reservasiPanel.setBackground(new java.awt.Color(234, 239, 234));

        tglResLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        tglResLabel.setForeground(new java.awt.Color(0, 0, 0));
        tglResLabel.setText("Tanggal Reservasi");

        tglResInput.setText("dd/mm/yyyy");

        javax.swing.GroupLayout reservasiPanelLayout = new javax.swing.GroupLayout(reservasiPanel);
        reservasiPanel.setLayout(reservasiPanelLayout);
        reservasiPanelLayout.setHorizontalGroup(
            reservasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservasiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reservasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglResLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tglResInput, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        reservasiPanelLayout.setVerticalGroup(
            reservasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservasiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tglResLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tglResInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        cancelBtn.setBackground(new java.awt.Color(153, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Batal");
        cancelBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        cancelBtn.setBorderPainted(false);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        tableReservasi.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        tableReservasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableReservasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableReservasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableReservasi);

        jmlTamuPanel.setBackground(new java.awt.Color(234, 239, 234));

        jmlTamuLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jmlTamuLabel.setForeground(new java.awt.Color(0, 0, 0));
        jmlTamuLabel.setText("Jumlah Tamu");

        javax.swing.GroupLayout jmlTamuPanelLayout = new javax.swing.GroupLayout(jmlTamuPanel);
        jmlTamuPanel.setLayout(jmlTamuPanelLayout);
        jmlTamuPanelLayout.setHorizontalGroup(
            jmlTamuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmlTamuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jmlTamuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jmlTamuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jmlTamuInput, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jmlTamuPanelLayout.setVerticalGroup(
            jmlTamuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmlTamuPanelLayout.createSequentialGroup()
                .addComponent(jmlTamuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jmlTamuInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        saveBtn.setBackground(new java.awt.Color(22, 52, 122));
        saveBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Simpan");
        saveBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        saveBtn.setBorderPainted(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(contentPanelLayout.createSequentialGroup()
                            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tanggalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pegawaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tamuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(135, 135, 135)
                            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(durasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jmlTamuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(reservasiPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jmlTamuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pegawaiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(durasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reservasiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(contentPanelLayout.createSequentialGroup()
                        .addComponent(tamuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tanggalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(headerPegawaiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headerReservasi1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(headerReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPegawaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(headerReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerReservasi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try{
            inputKosongException();
            numberFormatException();
            
            int selectedIndexPegawai = pegawaiDropDown.getSelectedIndex();
            int selectedIndexTamu = tamuDropDown.getSelectedIndex();
            Pegawai selectedPegawai = listPegawai.get(selectedIndexPegawai);
            Tamu selectedTamu = listTamu.get(selectedIndexTamu);
            
            int hargaHotel=120000;
            float subTotal, totalHarga, pajak=0.1f, hitung, totalPajak;
            
            if(Integer.parseInt(jmlTamuInput.getText())%2==0){
                hitung = Integer.parseInt(jmlTamuInput.getText())/2;
            }
            else{
                hitung = (Integer.parseInt(jmlTamuInput.getText())/2)+1;
            }
            
            subTotal = (hitung * hargaHotel)*Integer.parseInt(durasiInput.getText());
            totalPajak = subTotal * pajak;
            totalHarga = subTotal + totalPajak;
            
            if(action.equals("Tambah")){
                Reservasi r = new Reservasi(tglCheckInput.getText(),
                                            Integer.parseInt(durasiInput.getText()), 
                                            Integer.parseInt(jmlTamuInput.getText()),
                                            totalHarga,
                                            tglResInput.getText(), 
                                            selectedPegawai,
                                            selectedTamu);
                reservasiControl.insertDataReservasi(r);
            }else if(action.equals("Ubah")){
                Reservasi r = new Reservasi(selectedId, 
                                            tglCheckInput.getText(),
                                            Integer.parseInt(durasiInput.getText()), 
                                            Integer.parseInt(jmlTamuInput.getText()),
                                            totalHarga,
                                            tglResInput.getText(), 
                                            selectedPegawai,
                                            selectedTamu);
                reservasiControl.updateDataReservasi(r);
            }
            clearText();
            showReservasi();
            setComponent(false);
            setEditDeleteBtn(false);
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }catch(NumberFormatException e2){
            JOptionPane.showMessageDialog(this, e2.message());
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void homePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMouseClicked
        HomeView hv = new HomeView();
        this.dispose();
        hv.setVisible(true);
    }//GEN-LAST:event_homePanelMouseClicked

    private void transaksiPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transaksiPanelMouseClicked
        TransaksiView tv = new TransaksiView();
        this.dispose();
        tv.setVisible(true);
    }//GEN-LAST:event_transaksiPanelMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        setComponent(true);
        clearText();
        
        searchInput.setText("");
        action = "Tambah";
        pegawaiDropDown.setSelectedIndex(0);
        tamuDropDown.setSelectedIndex(0);
    }//GEN-LAST:event_addBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        setComponent(true);
        action = "Ubah";
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,
            "Apakah yakin ingin menghapus data Reservasi? ", "Konfirmasi",
            JOptionPane.YES_NO_OPTION);
        
        if(getAnswer == JOptionPane.YES_OPTION){
            try{
                reservasiControl.deleteDataReservasi(selectedId);
                clearText();
                showReservasi();
                setComponent(false);
                setEditDeleteBtn(false);
                JOptionPane.showMessageDialog(null, "Data Reservasi berhasil dihapus!");
            }catch(Exception  e){
                System.out.println("Error : " + e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Data Reservasi tidak jadi dihapus!");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        setEditDeleteBtn(false);
        setComponent(false);
        
        try{
            TableReservasi reservasi = reservasiControl.showReservasi(searchInput.getText());
            if(reservasi.getRowCount() == 0){
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data Reservasi tidak ditemukan!",
                     "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
                tableReservasi.setModel(reservasi);
            }
            clearText();
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void tableReservasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReservasiMouseClicked
        int indexPegawai = -1;
        int indexTamu = -1;
        setEditDeleteBtn(true);
        setComponent(false);
        
        int clickedRow = tableReservasi.getSelectedRow();
        TableModel tableModel = tableReservasi.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        tglCheckInput.setText(tableModel.getValueAt(clickedRow, 3).toString());
        durasiInput.setText(tableModel.getValueAt(clickedRow, 4).toString());
        jmlTamuInput.setText(tableModel.getValueAt(clickedRow, 5).toString());
        tglResInput.setText(tableModel.getValueAt(clickedRow, 7).toString());

        String id_pegawai = tableModel.getValueAt(clickedRow, 1).toString();
        for(Pegawai pegawai: listPegawai){
            if(pegawai.getId().equals(id_pegawai)){
                indexPegawai = listPegawai.indexOf(pegawai);
            }
        }
        pegawaiDropDown.setSelectedIndex(indexPegawai);
        
        int id_tamu = Integer.parseInt(tableModel.getValueAt(clickedRow, 2).toString());
        for(Tamu tamu: listTamu){
            if(tamu.getId() == id_tamu){
                indexTamu = listTamu.indexOf(tamu);
            }
        }
        tamuDropDown.setSelectedIndex(indexTamu);
    }//GEN-LAST:event_tableReservasiMouseClicked

    private void pegawaiDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegawaiDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pegawaiDropDownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservasiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservasiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservasiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservasiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservasiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField durasiInput;
    private javax.swing.JLabel durasiLabel;
    private javax.swing.JPanel durasiPanel;
    private javax.swing.JButton editBtn;
    private javax.swing.JPanel headerPegawaiPanel;
    private javax.swing.JPanel headerReservasi;
    private javax.swing.JPanel headerReservasi1;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel hotelIcon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jmlTamuInput;
    private javax.swing.JLabel jmlTamuLabel;
    private javax.swing.JPanel jmlTamuPanel;
    private javax.swing.JComboBox<Pegawai> pegawaiDropDown;
    private javax.swing.JLabel pegawaiLabel;
    private javax.swing.JPanel pegawaiPanel;
    private javax.swing.JLabel reservasiLabel;
    private javax.swing.JPanel reservasiPanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JTable tableReservasi;
    private javax.swing.JComboBox<Tamu> tamuDropDown;
    private javax.swing.JLabel tamuLabel;
    private javax.swing.JPanel tamuPanel;
    private javax.swing.JPanel tanggalPanel;
    private javax.swing.JTextField tglCheckInput;
    private javax.swing.JLabel tglCheckLabel;
    private javax.swing.JTextField tglResInput;
    private javax.swing.JLabel tglResLabel;
    private javax.swing.JLabel transaksiIcon;
    private javax.swing.JLabel transaksiLabel;
    private javax.swing.JPanel transaksiPanel;
    // End of variables declaration//GEN-END:variables
}
