package view;

import control.ReservasiControl;
import control.PegawaiControl;
import control.TransaksiControl;
import java.util.List;
import javax.swing.JOptionPane; 
import javax.swing.table.TableModel;
import model.Reservasi;
import model.Pegawai;
import model.Transaksi;
import table.TableTransaksi;

public class TransaksiView extends javax.swing.JFrame {
    private ReservasiControl reservasiControl;
    private PegawaiControl pegawaiControl;
    private TransaksiControl transaksiControl;
    List<Pegawai> listPegawai;
    List<Reservasi> listReservasi;
    String action = null;
    int selectedId = 0;
    
    public TransaksiView() {
        initComponents();
        setComponent(false);
        setPembayaran(false);
        setEditDeleteBtn(false);
        reservasiControl = new ReservasiControl();
        pegawaiControl = new PegawaiControl();
        transaksiControl = new TransaksiControl();
        showTransaksi();
        setReservasiToDropDown();
        setPegawaiToDropDown();
        bayarBtn.setEnabled(false);
    }
    
    public void setReservasiToDropDown(){
        listReservasi = reservasiControl.showListReservasi();
        for(int i=0; i<listReservasi.size(); i++){
            reservasiDropDown.addItem(listReservasi.get(i));
        }
    }
    
    public void setPegawaiToDropDown(){
        listPegawai = pegawaiControl.showListPegawai();
        for(int i=0; i<listPegawai.size(); i++){
            pegawaiDropDown.addItem(listPegawai.get(i));
        }
    }
    
    public void setComponent(boolean value){
        reservasiDropDown.setEnabled(value);
        pegawaiDropDown.setEnabled(value);
    }
    
    public void setFinish(boolean value){
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
    }
    
    public void setPembayaran(boolean value){
        jRadioCash.setEnabled(value);
        jRadioEWallet.setEnabled(value);
        jRadioCredit.setEnabled(value);
        jRadioDebit.setEnabled(value);
    }
     
    public void setEditDeleteBtn(boolean value){
        deleteBtn.setEnabled(value);
    }
    
    public void clearText(){
        reservasiDropDown.setSelectedItem(ABORT);
        pegawaiDropDown.setSelectedItem(ABORT);      
        
        searchInput.setText("");
    }
    
    public void showTransaksi(){
        tableTransaksi.setModel(transaksiControl.showTransaksi(""));
    }
    
//    public void pilihanKosongException() throws PilihanKosongException{
//        if(!jRadioCash.isSelected() && !jRadioEWallet.isSelected() &&
//           !jRadioCredit.isSelected() && !jRadioDebit.isSelected()){
//            throw new PilihanKosongException();
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bayarBtnGroup = new javax.swing.ButtonGroup();
        headerPegawaiPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        homeicon = new javax.swing.JLabel();
        homelabel = new javax.swing.JLabel();
        hotelIcon = new javax.swing.JLabel();
        reservasiPanel = new javax.swing.JPanel();
        reservasiIcon = new javax.swing.JLabel();
        reservasiLabel = new javax.swing.JLabel();
        headerReservasi = new javax.swing.JPanel();
        transaksiLabel = new javax.swing.JLabel();
        searchInput = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        headerReservasi1 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        contentPanel1 = new javax.swing.JPanel();
        idReservasiPanel = new javax.swing.JPanel();
        idreservasiLabel = new javax.swing.JLabel();
        reservasiDropDown = new javax.swing.JComboBox<>();
        MetodePanel = new javax.swing.JPanel();
        jRadioCash = new javax.swing.JRadioButton();
        jRadioEWallet = new javax.swing.JRadioButton();
        jRadioCredit = new javax.swing.JRadioButton();
        jRadioDebit = new javax.swing.JRadioButton();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        bayarBtn = new javax.swing.JButton();
        DurasiLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pegawaiDropDown = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerPegawaiPanel.setBackground(new java.awt.Color(255, 255, 255));

        homePanel.setBackground(new java.awt.Color(102, 153, 0));
        homePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePanelMouseClicked(evt);
            }
        });

        homeicon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/home.png"))); // NOI18N

        homelabel.setBackground(new java.awt.Color(255, 255, 255));
        homelabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        homelabel.setForeground(new java.awt.Color(255, 255, 255));
        homelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homelabel.setText("Home");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeicon, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
            .addComponent(homelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeicon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(homelabel)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        hotelIcon.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        hotelIcon.setForeground(new java.awt.Color(255, 255, 255));
        hotelIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hotel.png"))); // NOI18N
        hotelIcon.setText(".");

        reservasiPanel.setBackground(new java.awt.Color(102, 153, 0));
        reservasiPanel.setPreferredSize(new java.awt.Dimension(127, 163));
        reservasiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservasiPanelMouseClicked(evt);
            }
        });

        reservasiIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservasiIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/book.png"))); // NOI18N

        reservasiLabel.setBackground(new java.awt.Color(255, 255, 255));
        reservasiLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        reservasiLabel.setForeground(new java.awt.Color(255, 255, 255));
        reservasiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservasiLabel.setText("Reservasi ");

        javax.swing.GroupLayout reservasiPanelLayout = new javax.swing.GroupLayout(reservasiPanel);
        reservasiPanel.setLayout(reservasiPanelLayout);
        reservasiPanelLayout.setHorizontalGroup(
            reservasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(reservasiIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reservasiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        reservasiPanelLayout.setVerticalGroup(
            reservasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservasiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reservasiIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reservasiLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout headerPegawaiPanelLayout = new javax.swing.GroupLayout(headerPegawaiPanel);
        headerPegawaiPanel.setLayout(headerPegawaiPanelLayout);
        headerPegawaiPanelLayout.setHorizontalGroup(
            headerPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPegawaiPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(hotelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reservasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        headerPegawaiPanelLayout.setVerticalGroup(
            headerPegawaiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPegawaiPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(hotelIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(homePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(reservasiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        headerReservasi.setBackground(new java.awt.Color(234, 239, 234));
        headerReservasi.setForeground(new java.awt.Color(255, 255, 255));
        headerReservasi.setPreferredSize(new java.awt.Dimension(801, 103));

        transaksiLabel.setFont(new java.awt.Font("Futura Md BT", 1, 36)); // NOI18N
        transaksiLabel.setForeground(new java.awt.Color(0, 0, 0));
        transaksiLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        transaksiLabel.setText("  Transaksi ");

        searchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInputActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(22, 52, 122));
        searchBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Cari");
        searchBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchBtn.setBorderPainted(false);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerReservasiLayout = new javax.swing.GroupLayout(headerReservasi);
        headerReservasi.setLayout(headerReservasiLayout);
        headerReservasiLayout.setHorizontalGroup(
            headerReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerReservasiLayout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addComponent(transaksiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerReservasiLayout.setVerticalGroup(
            headerReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerReservasiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transaksiLabel)
                .addGap(4, 4, 4)
                .addGroup(headerReservasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        headerReservasi1.setBackground(new java.awt.Color(234, 239, 234));
        headerReservasi1.setForeground(new java.awt.Color(255, 255, 255));
        headerReservasi1.setPreferredSize(new java.awt.Dimension(801, 103));

        addBtn.setBackground(new java.awt.Color(0, 153, 0));
        addBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Tambah");
        addBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addBtn.setBorderPainted(false);
        addBtn.setDefaultCapable(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(153, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Hapus");
        deleteBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        deleteBtn.setBorderPainted(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerReservasi1Layout = new javax.swing.GroupLayout(headerReservasi1);
        headerReservasi1.setLayout(headerReservasi1Layout);
        headerReservasi1Layout.setHorizontalGroup(
            headerReservasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerReservasi1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(headerReservasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        headerReservasi1Layout.setVerticalGroup(
            headerReservasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerReservasi1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        contentPanel1.setBackground(new java.awt.Color(234, 239, 234));

        idReservasiPanel.setBackground(new java.awt.Color(234, 239, 234));

        idreservasiLabel.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        idreservasiLabel.setForeground(new java.awt.Color(0, 0, 0));
        idreservasiLabel.setText("Tanggal Check In");

        reservasiDropDown.setBorder(null);

        javax.swing.GroupLayout idReservasiPanelLayout = new javax.swing.GroupLayout(idReservasiPanel);
        idReservasiPanel.setLayout(idReservasiPanelLayout);
        idReservasiPanelLayout.setHorizontalGroup(
            idReservasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idReservasiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(idReservasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reservasiDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(idReservasiPanelLayout.createSequentialGroup()
                        .addComponent(idreservasiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 174, Short.MAX_VALUE)))
                .addContainerGap())
        );
        idReservasiPanelLayout.setVerticalGroup(
            idReservasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(idReservasiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idreservasiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservasiDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MetodePanel.setBackground(new java.awt.Color(234, 239, 234));

        bayarBtnGroup.add(jRadioCash);
        jRadioCash.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        jRadioCash.setForeground(new java.awt.Color(0, 0, 0));
        jRadioCash.setText("Cash");

        bayarBtnGroup.add(jRadioEWallet);
        jRadioEWallet.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        jRadioEWallet.setForeground(new java.awt.Color(0, 0, 0));
        jRadioEWallet.setText("E-Wallet");
        jRadioEWallet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioEWalletActionPerformed(evt);
            }
        });

        bayarBtnGroup.add(jRadioCredit);
        jRadioCredit.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        jRadioCredit.setForeground(new java.awt.Color(0, 0, 0));
        jRadioCredit.setText("Kartu Credit");

        bayarBtnGroup.add(jRadioDebit);
        jRadioDebit.setFont(new java.awt.Font("Futura Md BT", 0, 12)); // NOI18N
        jRadioDebit.setForeground(new java.awt.Color(0, 0, 0));
        jRadioDebit.setText("Kartu Debit");

        javax.swing.GroupLayout MetodePanelLayout = new javax.swing.GroupLayout(MetodePanel);
        MetodePanel.setLayout(MetodePanelLayout);
        MetodePanelLayout.setHorizontalGroup(
            MetodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MetodePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jRadioCash, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioEWallet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioCredit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioDebit)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        MetodePanelLayout.setVerticalGroup(
            MetodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MetodePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MetodePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioCash)
                    .addComponent(jRadioEWallet)
                    .addComponent(jRadioCredit)
                    .addComponent(jRadioDebit))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        cancelBtn.setBackground(new java.awt.Color(153, 0, 0));
        cancelBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Batal");
        cancelBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cancelBtn.setBorderPainted(false);
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(22, 52, 122));
        saveBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Simpan");
        saveBtn.setBorderPainted(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);

        bayarBtn.setBackground(new java.awt.Color(102, 153, 0));
        bayarBtn.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        bayarBtn.setForeground(new java.awt.Color(255, 255, 255));
        bayarBtn.setText("Bayar");
        bayarBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        bayarBtn.setBorderPainted(false);
        bayarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarBtnActionPerformed(evt);
            }
        });

        DurasiLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        DurasiLabel.setForeground(new java.awt.Color(0, 0, 0));
        DurasiLabel.setText("Metode Pembayaran");

        jPanel1.setBackground(new java.awt.Color(234, 239, 234));

        jLabel1.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Resepsionis");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 237, Short.MAX_VALUE))
                    .addComponent(pegawaiDropDown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pegawaiDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contentPanel1Layout = new javax.swing.GroupLayout(contentPanel1);
        contentPanel1.setLayout(contentPanel1Layout);
        contentPanel1Layout.setHorizontalGroup(
            contentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanel1Layout.createSequentialGroup()
                .addGroup(contentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(contentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(contentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(contentPanel1Layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addComponent(MetodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(saveBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14))))
                            .addGroup(contentPanel1Layout.createSequentialGroup()
                                .addComponent(idReservasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(105, 105, 105)
                                .addGroup(contentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bayarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DurasiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentPanel1Layout.setVerticalGroup(
            contentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(contentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contentPanel1Layout.createSequentialGroup()
                        .addComponent(idReservasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(contentPanel1Layout.createSequentialGroup()
                        .addComponent(bayarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(DurasiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(contentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(MetodePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(contentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(headerPegawaiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerReservasi1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(headerPegawaiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headerReservasi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerReservasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(contentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchInputActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setPembayaran(false);
        setFinish(false);
        setEditDeleteBtn(false);
        clearText();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        int selectedIndexPegawai = pegawaiDropDown.getSelectedIndex();
        int selectedIndexReservasi = reservasiDropDown.getSelectedIndex();
        Pegawai selectedPegawai = listPegawai.get(selectedIndexPegawai);
        Reservasi selectedReservasi = listReservasi.get(selectedIndexReservasi);
        
        String metodePembayaran = "-";
        String status = "Check In";
        
        
        if(action.equals("Tambah")){
            Transaksi t = new Transaksi(metodePembayaran,
                                        status,  
                                        selectedPegawai,
                                        selectedReservasi);
            transaksiControl.insertDataTransaksi(t);
        }else if(action.equals("Bayar")){
            status = "Check Out";
            
            if(jRadioCash.isSelected()==true){
                metodePembayaran = "Cash";
            }else if(jRadioEWallet.isSelected()==true){
                metodePembayaran = "E-Wallet";
            }else if(jRadioCredit.isSelected()==true){
                metodePembayaran = "Kartu Credit";
            }else{
                metodePembayaran = "Kartu Debit";
            }
            
            Transaksi t = new Transaksi(selectedId, 
                                        metodePembayaran,
                                        status,  
                                        selectedPegawai,
                                        selectedReservasi);
            transaksiControl.updateDataTransaksi(t);
        }
        clearText();
        showTransaksi();
        setComponent(false);
        setEditDeleteBtn(false);
    }//GEN-LAST:event_saveBtnActionPerformed

    private void jRadioEWalletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioEWalletActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioEWalletActionPerformed

    private void homePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMouseClicked
        HomeView hv = new HomeView();
        this.dispose();
        hv.setVisible(true);
    }//GEN-LAST:event_homePanelMouseClicked

    private void reservasiPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservasiPanelMouseClicked
        ReservasiView rv = new ReservasiView();
        this.dispose();
        rv.setVisible(true);
    }//GEN-LAST:event_reservasiPanelMouseClicked

    private void bayarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarBtnActionPerformed
        setComponent(false);
        setFinish(true);
        setPembayaran(true);
        action = "Bayar";
    }//GEN-LAST:event_bayarBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        setComponent(true);
        setPembayaran(false);
        setFinish(true);
        clearText();
        
        searchInput.setText("");
        action = "Tambah";
        reservasiDropDown.setSelectedIndex(0);
        pegawaiDropDown.setSelectedIndex(0);
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try{
            int clickedRow = tableTransaksi.getSelectedRow();
            TableModel tableModel = tableTransaksi.getModel();
              
            if(tableModel.getValueAt(clickedRow, 5).equals("Check Out")){
                transaksiControl.deleteDataTransaksi(selectedId);
                clearText();
                showTransaksi();
                setComponent(false);
                setEditDeleteBtn(false);
                JOptionPane.showMessageDialog(null, "Data Transaksi berhasil dihapus!");
            }else{
                JOptionPane.showMessageDialog(null, "Tamu belum Check Out!");
            }
        }catch(Exception  e){
            System.out.println("Error : " + e.getMessage());
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        setEditDeleteBtn(false);
        setComponent(false);
        
        try{
            TableTransaksi transaksi = transaksiControl.showTransaksi(searchInput.getText());
            if(transaksi.getRowCount() == 0){
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data Transkasi tidak ditemukan!",
                     "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
                tableTransaksi.setModel(transaksi);
            }
            clearText();
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
        int indexReservasi = -1;
        int indexPegawai = -1;
        setEditDeleteBtn(true);
        setComponent(false);
        bayarBtn.setEnabled(true);
        
        int clickedRow = tableTransaksi.getSelectedRow();
        TableModel tableModel = tableTransaksi.getModel();
        
        selectedId = Integer.parseInt(tableModel.getValueAt(clickedRow, 0).toString());
        
        String metodePembayaran = tableModel.getValueAt(clickedRow, 3).toString();
        switch(metodePembayaran){
            case "Cash":
                jRadioCash.setSelected(true);
                jRadioEWallet.setSelected(false);
                jRadioCredit.setSelected(false);
                jRadioDebit.setSelected(false);
                break;
            case "E-Wallet":
                jRadioCash.setSelected(false);
                jRadioEWallet.setSelected(true);
                jRadioCredit.setSelected(false);
                jRadioDebit.setSelected(false);
                break;
            case "Kartu Credit":
                jRadioCash.setSelected(false);
                jRadioEWallet.setSelected(false);
                jRadioCredit.setSelected(true);
                jRadioDebit.setSelected(false);
                break;
            case "Kartu Debit":
                jRadioCash.setSelected(false);
                jRadioEWallet.setSelected(false);
                jRadioCredit.setSelected(false);
                jRadioDebit.setSelected(true);
                break;
        }
        String id_pegawai = tableModel.getValueAt(clickedRow, 1).toString();
        for(Pegawai pegawai: listPegawai){
            if(pegawai.getId().equals(id_pegawai)){
                indexPegawai = listPegawai.indexOf(pegawai);
            }
        }
        pegawaiDropDown.setSelectedIndex(indexPegawai);
        
        int id_reservasi = Integer.parseInt(tableModel.getValueAt(clickedRow, 2).toString());
        for(Reservasi reservasi: listReservasi){
            if(reservasi.getId() == id_reservasi){
                indexReservasi = listReservasi.indexOf(reservasi);
            }
        }
        reservasiDropDown.setSelectedIndex(indexReservasi);
    }//GEN-LAST:event_tableTransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DurasiLabel;
    private javax.swing.JPanel MetodePanel;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton bayarBtn;
    private javax.swing.ButtonGroup bayarBtnGroup;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JPanel contentPanel1;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JPanel headerPegawaiPanel;
    private javax.swing.JPanel headerReservasi;
    private javax.swing.JPanel headerReservasi1;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel homeicon;
    private javax.swing.JLabel homelabel;
    private javax.swing.JLabel hotelIcon;
    private javax.swing.JPanel idReservasiPanel;
    private javax.swing.JLabel idreservasiLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioCash;
    private javax.swing.JRadioButton jRadioCredit;
    private javax.swing.JRadioButton jRadioDebit;
    private javax.swing.JRadioButton jRadioEWallet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Pegawai> pegawaiDropDown;
    private javax.swing.JComboBox<Reservasi> reservasiDropDown;
    private javax.swing.JLabel reservasiIcon;
    private javax.swing.JLabel reservasiLabel;
    private javax.swing.JPanel reservasiPanel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchInput;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JLabel transaksiLabel;
    // End of variables declaration//GEN-END:variables
}
